import Head from 'next/head'
import Image from 'next/image'
import Banner from '../src/components/Banner'
import HomePage from '../src/components/Home'
import Products from './products'
import Testimonials from './testimonials'
import Footer from './contact'
import About from './about'
export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
       <HomePage/>
      <About/>
       <Products/>
       <Testimonials/>
       <Footer/>
      </main>
    </div>
  )
}
